apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: migrate-sfm-rules
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Change to LoadBalancer or ClusterIP if needed
